title: 夢沉抹大拉
description: 一个追寻抹大拉之地的geeker
meta_description: 生命不息，折腾不止

remote_theme: pages-themes/hacker@v0.2.0

paginate: 10

# Use the following plug-ins
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-paginate

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://blog.imaou.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/upbit/upbit.github.io/master/assets/images/profile.png

show_downloads: false
google_analytics: 53731588
